### ISSUE TITLE
Error in R_nc4_open

### ISSUE THREAD

**Issue by tanagarth79** [aemon-j/LakeEnsemblR#251] opened 2022-09-14 07:48 UTC
Hi everybody,

After running the ensemble lake models, I get this error:

> Loading water temperature observations...[2022-09-14 07:43:11]
> Finished loading water temperature observations![2022-09-14 07:43:11]
> Loading ice observations...
> Finished loading ice observations!
> Running models... (Have you tried parallelizing?) [2022-09-14 07:43:11]
> FLake does not support simulation of changing water level.
> FLake run is complete! [2022-09-14 07:43:11]
> GLM run is complete! [2022-09-14 07:43:12]
> Error in R_nc4_open: No such file or directory
> Error in nc_open(file, readunlim = TRUE) : 
>   Error in nc_open trying to open file ./GLM/output/output.nc (return_on_error= FALSE )

Does anybody know the cause?

Thanks in advance for your help!

Fabien Cremona.

**Comment by JFeldbauer** [comment] 2022-09-14 07:52
Hello Fabien,
this error usually means that GLM crashed while running und thus the GLM output (a netcdf file) is either missing or can not be read from. To get more information you can try to just run GLM by using:
`GLM3r::run_glm(sim_folder = "GLM", verbose = TRUE)`
from your simulation folder. The output from GLM might give you some more information why it crahses, usually that is related to the used boundary conditions.
Hope that helps,
Johannes

**Comment by JFeldbauer** [comment] 2022-09-14 07:58
hm I'm not sure. you could first try to run the other models and see if the problem is just specific to GLM

**Comment by tanagarth79** [comment] 2022-09-14 07:59
OK, I will try this, thanks.

**Comment by tanagarth79** [comment] 2022-09-14 08:04
Yes, it worked without GLM. 

> 
> Loading water temperature observations...[2022-09-14 08:00:33]
> Finished loading water temperature observations![2022-09-14 08:00:33]
> Loading ice observations...
> Finished loading ice observations!
> Running models... (Have you tried parallelizing?) [2022-09-14 08:00:33]
> FLake does not support simulation of changing water level.
> FLake run is complete! [2022-09-14 08:00:33]
> GOTM run is complete! [2022-09-14 08:00:34]
> Interpolating GOTM temp to include obs depths... [2022-09-14 08:00:34]
> Finished interpolating! [2022-09-14 08:00:34]
> Simstrat run is complete! [2022-09-14 08:00:34]
> Interpolating Simstrat temp to include obs depths... [2022-09-14 08:00:34]
> Finished interpolating! [2022-09-14 08:00:34]
> [1] "Running MyLake from 01/01/15 to 01/31/15..."
> [1] "Ice-on,  01/04/15"
>    user  system elapsed 
>    0.26    0.00    0.27 
> MyLake run is complete! [2022-09-14 08:00:34]
> MyLake does not support simulation of changing water level.
> Model run complete![2022-09-14 08:00:34]
> Creating directory for output: ./output
> Writing NetCDF file... [2022-09-14 08:00:34]
> Finished writing NetCDF file [2022-09-14 08:00:34]
> There were 16 warnings (use warnings() to see them)
>

**Comment by JFeldbauer** [comment] 2022-09-14 08:07
can you post the whole output from the GLM run

**Comment by tanagarth79** [comment] 2022-09-14 08:10
For the run, I get only what I posted above. For the config export I get this:

> export_dirs complete!
> Replaced time start 2015-01-0100:00:00 with 2015-01-01 00:00:00
> Replaced time stop 2015-01-3100:00:00 with 2015-01-31 00:00:00
> Replaced time dt 3600 with 3600
> Replaced Simulation Start year 2015, with 2015
> Replaced Simulation Start d 0, with 0
> Replaced Simulation End d 30, with 30
> Replaced Simulation Timestep s 3600, with 3600
> export_time complete!
> Replaced SIMULATION_PARAMS h_ML_in 0.6976, with 0.6976
> Replaced LAKE_PARAMS depth_w_lk 0.6976, with 0.6976
> Replaced LAKE_PARAMS latitude_lk 58.16, with 58.16
> Replaced location name Vortsjarv with Vortsjarv
> Replaced location latitude 58.16 with 58.16
> Replaced location longitude 26.2 with 26.2
> Replaced location depth 6 with 6
> Replaced grid nlev 12 with 12
> Replaced ice model 2 with 2
> Replaced location hypsograph hypsograph.dat with hypsograph.dat
> Replaced Input Grid 12, with 12
> Replaced Input Morphology "hypsograph.dat", with "hypsograph.dat"
> Replaced ModelParameters lat 58.16, with 58.16
> Replaced ModelConfig IceModel 1, with 1
> Replaced ModelParameters a_seiche 0.070779190257756, with 0.070779190257756
> export_location complete!
> Replaced METEO outputfile 'output/output.dat', with 'output/output.dat'
> Replaced output output time_step: 24 with 24
> Replaced output output time_unit: hour with hour
> Replaced output time_method mean with mean
> Replaced output format netcdf with netcdf
> Replaced Output Path "output", with "output"
> Replaced Output Depths 0.5, with 0.5
> Replaced Output Times 24, with 24
> export_output_settings complete!
> Loading met data...[2022-09-14 07:43:06]
> Finished loading met data![2022-09-14 07:43:06]
> Replaced SIMULATION_PARAMS del_time_lk 3600, with 3600
> Replaced SIMULATION_PARAMS time_step_number 720, with 720
> Replaced METEO meteofile 'all_meteo_file.dat', with 'all_meteo_file.dat'
> FLake: Created file ./FLake/all_meteo_file.dat
> GLM: Created file ./GLM/meteo_file.csv
> Replaced u10 column 1 with 1
> Replaced u10 scale_factor 1 with 1
> Replaced v10 column 2 with 2
> Replaced v10 scale_factor 1 with 1
> Replaced airp column 3 with 3
> Replaced airp scale_factor 1 with 1
> Replaced airt column 4 with 4
> Replaced airt scale_factor 1 with 1
> Replaced cloud column 6 with 6
> Replaced cloud scale_factor 1 with 1
> Replaced swr column 7 with 7
> Replaced swr scale_factor 1 with 1
> Replaced precip column 8 with 8
> Replaced precip scale_factor 1 with 1
> Replaced hum column 5 with 5
> Replaced hum type 1 with 1
> Replaced hum scale_factor 1 with 1
> Replaced u10 file meteo_file.dat with meteo_file.dat
> Replaced v10 file meteo_file.dat with meteo_file.dat
> Replaced airp file meteo_file.dat with meteo_file.dat
> Replaced airt file meteo_file.dat with meteo_file.dat
> Replaced cloud file meteo_file.dat with meteo_file.dat
> Replaced swr file meteo_file.dat with meteo_file.dat
> Replaced precip file meteo_file.dat with meteo_file.dat
> Replaced hum file meteo_file.dat with meteo_file.dat
> GOTM: Created file ./GOTM/meteo_file.dat
> Replaced ModelConfig SnowModel 1, with 1
> Replaced ModelParameters p_air 1005, with 1005
> Replaced ModelConfig Forcing 5, with 5
> Replaced Input Forcing "meteo_file.dat", with "meteo_file.dat"
> Simstrat: Created file ./Simstrat/meteo_file.dat
> MyLake: Created file ./MyLake/meteo_file.dat
> export_meteo complete!
> Loading wtemp_file...
> Replaced SIMULATION_PARAMS T_wML_in 0.3745, with 0.3745
> Replaced SIMULATION_PARAMS T_bot_in 0.6472, with 0.6472
> Replaced SIMULATION_PARAMS h_ML_in 0.6976, with 0.6976
> FLake: Input initial conditions into ./FLake/flake.nml
> GLM: Input initial conditions into ./GLM/glm3.nml
> Replaced temperature file init_cond.dat with init_cond.dat
> Replaced temperature method 2 with 2
> Replaced temperature column 1 with 1
> GOTM: Created initial conditions file ./GOTM/init_cond.dat
> Replaced Input Initial conditions "init_cond.dat", with "init_cond.dat"
> Simstrat: Created initial conditions file ./Simstrat/init_cond.dat
> MyLake: Created initial conditions file ./MyLake/mylake.Rdata
>   depths  wtemp
> 1    0.5 0.3745
> 2    1.4 0.6472
> export_init_cond complete!
> Replaced TRANSPARENCY extincoef_optic 3.3, with 3.3
> Replaced g2 method 0 with 0
> Replaced g2 constant_value 0.303030303030303 with 0.303030303030303
> Replaced Input Absorption "light_absorption.dat", with "light_absorption.dat"
> export_extinction complete!
> Replaced inflow Qfromfile .true., with .true.
> Replaced mimic_3d zeta method: 3 with 3
> Replaced water_balance_method: 3 with 3
> Replaced streams inflow flow method: 2 with 2
> Replaced streams inflow temp method: 2 with 2
> Replaced streams inflow salt method: 2 with 2
> Replaced streams inflow flow file: inflow_file_1.dat with inflow_file_1.dat
> Replaced streams inflow temp file: inflow_file_1.dat with inflow_file_1.dat
> Replaced streams inflow salt file: inflow_file_1.dat with inflow_file_1.dat
> Replaced streams inflow_2 flow method: 2 with 2
> Replaced streams inflow_2 temp method: 2 with 2
> Replaced streams inflow_2 salt method: 2 with 2
> Replaced streams inflow_2 flow file: inflow_file_2.dat with inflow_file_2.dat
> Replaced streams inflow_2 temp file: inflow_file_2.dat with inflow_file_2.dat
> Replaced streams inflow_2 salt file: inflow_file_2.dat with inflow_file_2.dat
> Replaced streams inflow_3 flow method: 2 with 2
> Replaced streams inflow_3 temp method: 2 with 2
> Replaced streams inflow_3 salt method: 2 with 2
> Replaced streams inflow_3 flow file: inflow_file_3.dat with inflow_file_3.dat
> Replaced streams inflow_3 temp file: inflow_file_3.dat with inflow_file_3.dat
> Replaced streams inflow_3 salt file: inflow_file_3.dat with inflow_file_3.dat
> Replaced streams inflow_4 flow method: 2 with 2
> Replaced streams inflow_4 temp method: 2 with 2
> Replaced streams inflow_4 salt method: 2 with 2
> Replaced streams inflow_4 flow file: inflow_file_4.dat with inflow_file_4.dat
> Replaced streams inflow_4 temp file: inflow_file_4.dat with inflow_file_4.dat
> Replaced streams inflow_4 salt file: inflow_file_4.dat with inflow_file_4.dat
> Replaced streams outflow method: 1 with 1
> Replaced streams outflow zl: -3.7 with -3.7
> Replaced streams outflow zu: -2.7 with -2.7
> Replaced streams outflow flow method: 2 with 2
> Replaced streams outflow temp method: 0 with 0
> Replaced streams outflow salt method: 0 with 0
> Replaced streams outflow flow file: outflow_file_1.dat with outflow_file_1.dat
> Replaced streams outflow temp file: outflow_file_1.dat with outflow_file_1.dat
> Replaced streams outflow salt file: outflow_file_1.dat with outflow_file_1.dat
> Loading inflow data...
> Replaced inflow time_step_number 31, with 31
> FLake: Created file ./FLake/Tinflow
> GLM: Created file ./GLM/inflow_1.csv
> GLM: Created file ./GLM/inflow_2.csv
> GLM: Created file ./GLM/inflow_3.csv
> GLM: Created file ./GLM/inflow_4.csv
> GOTM: Created file ./GOTM/inflow_file_1.dat
> GOTM: Created file ./GOTM/inflow_file_2.dat
> GOTM: Created file ./GOTM/inflow_file_3.dat
> GOTM: Created file ./GOTM/inflow_file_4.dat
> Replaced ModelConfig InflowMode 1, with 1
> Simstrat: Created file ./Simstrat/Qin.dat
> MyLake: Created file ./MyLake/mylake.Rdata
> Loading outflow data...
> FLake does not need outflows, as mass fluxes are not considered.
> GLM: Created file ./GLM/outflow_1.csv
> GOTM: Created file ./GOTM/outflow_file_1.dat
> Replaced ModelConfig InflowMode 1, with 1
> Simstrat: Created outflow file ./Simstrat/Qout.dat
> MyLake does not need specific outflows, as it employs automatic overflow.
> export_flow complete!
> Replaced  fetch_lk 2000, with 2000
> Replaced  bsn_len 26221.16 with 34800
> Replaced  bsn_wid 13110.58 with 14800
> Replaced  k_min 3.6e-06 with 3.6e-06
> Replaced Phys.par C_shelter 1 with 0.15
> export_model_parameters complete!
> Warning messages:
> 1: In export_meteo(config_file = config_file, model = model, folder = folder) :
>   Meteo time step less than daily; averaging met file for MyLake simulation.
> 2: In calc_hmix(tmp, deps) : Warning:need more than 3 temperature values

**Comment by JFeldbauer** [comment] 2022-09-14 08:11
did you plot the output of the run without GLM, does it seem ok?

**Comment by tanagarth79** [comment] 2022-09-14 08:15
Yes, I plotted it, and the heatmap looks like this, something is probably wrong.
![heatmap](https://user-images.githubusercontent.com/16190177/190099367-e726c77c-70b8-4612-92af-5cb3d5ebb10a.jpeg)

**Comment by jorritmesman** [comment] 2022-09-14 08:40
I also don't yet understand what's going wrong, but your heat maps suggest that GOTM and Simstrat (and therefore probably also GLM) are gaining a lot of water in only a few days time. Could you check the magnitudes of your inflows and see if they are approximately the same as your outflow? Otherwise, could you see if you have the right unit for precipitation?

**Comment by tanagarth79** [comment] 2022-09-14 09:25
Hello Jorris, 
I checked the inflows and on average they are the same magnitude as outflow (18 vs 22 m3 s-1). Regarding the precipitation units, they are in millimeter per hour (totaling 580 mm in 2015, the year I have chosen for the simulation).

**Comment by jorritmesman** [comment] 2022-09-14 11:22
Perhaps you could send us your configuration file, your hypsograph, and the first month of your forcing files? Then we can run it as well and see what's going on.

**Comment by tanagarth79** [comment] 2022-09-14 11:38
Here they are
[vortsjarv.txt](https://github.com/aemon-j/LakeEnsemblR/files/9565936/vortsjarv.txt)
[vortsjarv_bathymetry_standard1.csv](https://github.com/aemon-j/LakeEnsemblR/files/9565937/vortsjarv_bathymetry_standard1.csv)
[vortsjarv_ice-height_standard1.csv](https://github.com/aemon-j/LakeEnsemblR/files/9565938/vortsjarv_ice-height_standard1.csv)
[vortsjarv_inflow_standard1.csv](https://github.com/aemon-j/LakeEnsemblR/files/9565939/vortsjarv_inflow_standard1.csv)
[vortsjarv_meteo_standard1.csv](https://github.com/aemon-j/LakeEnsemblR/files/9565940/vortsjarv_meteo_standard1.csv)
[vortsjarv_outflow_standard1.csv](https://github.com/aemon-j/LakeEnsemblR/files/9565941/vortsjarv_outflow_standard1.csv)
[vortsjarv_wtemp_profile_standard1.csv](https://github.com/aemon-j/LakeEnsemblR/files/9565942/vortsjarv_wtemp_profile_standard1.csv)

**Comment by jorritmesman** [comment] 2022-09-14 12:45
Okay, I seemingly have it working, but it seems to be something specific for GLM. 

I don't know why it now works, but based on the error I tried to play with the outflow settings and when I set the GLM `crest_factor` to 0.91, it seems to work, see attached. 
![Heatmap_LER](https://user-images.githubusercontent.com/42146440/190155957-48105330-06e9-4596-8e12-e7e8d880410a.png)

Also, I think there is an imbalance between your inflow and outflows, which results in the strong water level increase. You also double the discharge of the first stream by a factor 2 in the scaling_factors/all/inflow section. However, this was not related to the error. In the plot shown here I increased the outflow a factor 20, but you might want to look at a better solution.

To set the crest_factor to 0.91 from within the LER config file, add `crest_factor: 0.91` under the model_parameters/GLM section (right under `basin_wid`)

I should also say that it still didn't seem very stable, and the run sometimes failed. Since this seems to be a GLM-specific issue, I'm not sure if we can help more. @robertladwig, do you know more about this? You can use the files above to make a test run (just change the stop date to the end of January).

**Comment by robertladwig** [comment] 2022-09-14 13:00
I'll dig into this hopefully this Friday. @tanagarth79 are you sure your boundary conditions fulfill a mass balance for inflows and outflows? Or would you expect strong water level fluctuations in that shallow system?

**Comment by tanagarth79** [comment] 2022-09-14 14:59
@jorritmesman thank you for your time and for the suggestions ! I will implement these changes. @robertladwig @jorritmesman yes there is an imbalance between in and outflows as this lake has unregulated flow, meaning that water level changes are fluctuating much seasonally (high water level in spring after snowmelt, and often "negative" outflow because of the flat landscape). Shall I remove in/outflow as was suggested in the other issue thread, or shall I keep them in order to display water (in)balance of the system?

**Comment by jorritmesman** [comment] 2022-09-19 08:51
For now I'll close this issue, as it doesn't imply any required changes to the package itself, but of course don't hesitate to reach out to us if you encounter problems!

**Closed by jorritmesman** 2022-09-19 08:51 UTC
